# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI for Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      NNG_VERSION: 1.4.0
    runs-on: ubuntu-latest

    steps:
    - name: apt-update
      run: sudo apt-get update
    - name: install cmake and ninja
      run: sudo apt-get install cmake ninja-build

    - name: fetch nng v1.4.0
      run: wget "https://github.com/nanomsg/nng/archive/v${NNG_VERSION}.tar.gz"
    - name: unpack nng
      run: tar xvfz "v${NNG_VERSION}.tar.gz"
    - name: make cmake build dir
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: configure cmake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake "${GITHUB_WORKSPACE}/nng-${NNG_VERSION}" -DBUILD_SHARED_LIBS=yes -G Ninja
    - name: build nng
      working-directory: ${{github.workspace}}/build
      run: ninja
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      env:
        LD_LIBRARY_PATH: ${{github.workspace}}/build
      run: ./gradlew build
